### PR TITLE
replace libarchive dependency with Python standard library

### PR DESCRIPTION
**Pull request by csachs**
Pulled out of #10 and rebased to current main.

### CODE REVIEW

**Comment by whitequark** [comment]
Just to confirm; does this produce exactly the same archives as before? It looks like it would, but I want to ask to make sure.

**Comment by csachs** [comment]
Now that you mentioned it, the original variant passed directory entries on for ZIP files ...
I've force pushed the PR to fix this. Results match now for the current set of default wheels:

```
% ls 
main  pr
% for variant in *; do (cd $variant; pdm run make_wheels.py; cd ..;) 
# ...
% sha1sum main/dist/* pr/dist/*
25140e06d536e389a6f7738ddc6fbc5dfabfdab4  main/dist/ziglang-0.11.0-py3-none-macosx_10_9_x86_64.whl
c61864725ca16ec16c50612499772d7856bd2f44  main/dist/ziglang-0.11.0-py3-none-macosx_11_0_arm64.whl
0151ef48df78a794598d65d3d35084f257d4ccff  main/dist/ziglang-0.11.0-py3-none-manylinux_2_12_i686.manylinux2010_i686.musllinux_1_1_i686.whl
0a0c6665cf0f1c5464c126d7d0eeeccf40726df0  main/dist/ziglang-0.11.0-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl
1d9930dca0663e55b19b0458b2d6ff99007d2a4d  main/dist/ziglang-0.11.0-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.musllinux_1_1_aarch64.whl
685090e3a3dd00b01f9258b18ad14e65a4b0703b  main/dist/ziglang-0.11.0-py3-none-manylinux_2_17_armv7l.manylinux2014_armv7l.musllinux_1_1_armv7l.whl
36e59e098746644b89cd64d65db0bc78e79558ae  main/dist/ziglang-0.11.0-py3-none-win_amd64.whl
25140e06d536e389a6f7738ddc6fbc5dfabfdab4  pr/dist/ziglang-0.11.0-py3-none-macosx_10_9_x86_64.whl
c61864725ca16ec16c50612499772d7856bd2f44  pr/dist/ziglang-0.11.0-py3-none-macosx_11_0_arm64.whl
0151ef48df78a794598d65d3d35084f257d4ccff  pr/dist/ziglang-0.11.0-py3-none-manylinux_2_12_i686.manylinux2010_i686.musllinux_1_1_i686.whl
0a0c6665cf0f1c5464c126d7d0eeeccf40726df0  pr/dist/ziglang-0.11.0-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl
1d9930dca0663e55b19b0458b2d6ff99007d2a4d  pr/dist/ziglang-0.11.0-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.musllinux_1_1_aarch64.whl
685090e3a3dd00b01f9258b18ad14e65a4b0703b  pr/dist/ziglang-0.11.0-py3-none-manylinux_2_17_armv7l.manylinux2014_armv7l.musllinux_1_1_armv7l.whl
36e59e098746644b89cd64d65db0bc78e79558ae  pr/dist/ziglang-0.11.0-py3-none-win_amd64.whl
```

**Comment by whitequark** [comment]
Glad I asked then! That's good for me.

**Comment by whitequark** [comment]
Thank you!

**Pull request merged**
